#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get install -y haproxy

echo 'ENABLED=1' >> /etc/default/haproxy

printf %s "backend app_server
  balance roundrobin
  server 3161-web-01 35.243.156.27:80 check
  server 3161-web-02 35.237.17.86:80 check
frontend lb_server
  bind 0.0.0.0:80
  mode http
  default_backend app_server
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
