#!/usr/bin/env bash   
# Install Load Balancer
apt-get update
apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.1 --yes

apt-get -y install haproxy 

printf %s"global                                                                                                                            
        log /dev/log    local0                                                                                                    
        log /dev/log    local1 notice                                                                                             
        chroot /var/lib/haproxy                                                                                                   
        stats socket /run/haproxy/admin.sock mode 660 level admin                                                                 
        stats timeout 30s                                                                                                         
        user haproxy                                                                                                              
        group haproxy                                                                                                             
        daemon                                                                                                                    
        ca-base /etc/ssl/certs                                                                                                    
        crt-base /etc/ssl/private                                                                                                 
                                                                                                                                  
        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS                                                                                                      
        ssl-default-bind-options no-sslv3                                                                                         
                                                                                                                                  
defaults                                                                                                                          
        log     global                                                                                                            
        mode    http                                                                                                              
        option  httplog                                                                                                           
        option  dontlognull                                                                                                       
        timeout connect 5000                                                                                                      
        timeout client  50000                                                                                                     
        timeout server  50000                                                                                                     
        errorfile 400 /etc/haproxy/errors/400.http                                                                                
        errorfile 403 /etc/haproxy/errors/403.http                                                                                
        errorfile 408 /etc/haproxy/errors/408.http                                                                                
        errorfile 500 /etc/haproxy/errors/500.http                                                                                
        errorfile 502 /etc/haproxy/errors/502.http                                                                                
        errorfile 503 /etc/haproxy/errors/503.http                                                                                
        errorfile 504 /etc/haproxy/errors/504.http                                                                                
listen www        
   bind :80                                                                                                                  
        balance roundrobin                                                                                                        
        server gc-3161-web-02 104.196.174.128:80 check                                                                     
        server gc-3161-web-01 35.243.156.27:80 check      
" > /etc/haproxy/haproxy.cfg

service haproxy start                                                 
 #!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine to HAproxy
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
sudo sed -i '35 a \\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back' /etc/haproxy/haproxy.cfg
sudo sed -i '40 a \\nbackend http_back\n\tbalance roundrobin\n\tserver web-01 35.243.156.27:80 check\n\tserver web-02 104.196.174.128:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
