#!/usr/bin/env bash
# Installs Nginx with the following configurations:
apt-get -y update
apt-get -y install nginx
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
