#!/usr/bin/env bash 
# Intsaltion of Nginx
apt-get update -y 
apt-get install -y nginx
mkdir /usr/share/nginx/web
touch /usr/share/nginx/web/index.html
echo "Holberton School" > /usr/share/nginx/web/index.html
printf %s "
    server {
        listen      80 default_server;
        listen      [::]:80 default_server;
        location / {
            root      /usr/share/nginx/web/;
            index     index.html;
        }
      
    }
" > /etc/nginx/sites-available/default
service nginx restart
